// Spanish course data, extracted verbatim from the original App.jsx.
// Phase 1 moves this to content/es/lessons/*.json with a language-neutral schema.
export const UNITS = [
  {
    id: "basics",
    title: "The Basics",
    sub: "Small words, big power",
    emoji: "🧱",
    color: "#a8d8ea",
    lessons: [
      {
        id: "the",
        title: "the",
        emoji: "📌",
        en: ["the"],
        es: "el / la",
        pron: "ehl / lah",
        note: "Spanish has TWO words for 'the' — and there's a real reason why.",
        clusters: [
          { e: "the boy", s: "el niño", g: "m" },
          { e: "the girl", s: "la niña", g: "f" },
          { e: "the coffee", s: "el café", g: "m" },
          { e: "the music", s: "la música", g: "f" },
        ],
        placement: { en: ["the", "boy"], es: ["el", "niño"] },
        because: {
          title: 'Why two words for "the"?',
          explain:
            'Thousands of years ago, Latin sorted ALL nouns into two bins — like color-coded teams. They called them "masculine" and "feminine" but it has nothing to do with boy/girl. Think electrical plugs: Type A and Type B. The name is just a label.',
          key: 'Cheat code: words ending in -o go in the "el" bin. Words ending in -a go in the "la" bin.',
          fun: "German has THREE bins. English used to have them too but dropped them 800 years ago!",
          src: 'The real term is "grammatical gender." Linguists call it "noun class."',
        },
        practice: [
          { type: "pick", q: '"the boy" in Spanish…', a: "el niño", w: ["la niño", "el niña", "la niña"], h: "niño ends in -o → el" },
          { type: "pick", q: '"the music" — el or la?', a: "la música", w: ["el música", "un música", "el musica"], h: "música ends in -a → la" },
          { type: "match", q: "Match each phrase", pairs: [["the boy", "el niño"], ["the girl", "la niña"], ["the coffee", "el café"], ["the music", "la música"]] },
        ],
      },
      {
        id: "a_an",
        title: "a / an",
        emoji: "1️⃣",
        en: ["a", "an"],
        es: "un / una",
        pron: "oon / OO-nah",
        note: "Same two bins — different word.",
        clusters: [
          { e: "a boy", s: "un niño", g: "m" },
          { e: "a girl", s: "una niña", g: "f" },
          { e: "a cat", s: "un gato", g: "m" },
          { e: "a table", s: "una mesa", g: "f" },
        ],
        placement: { en: ["a", "cat"], es: ["un", "gato"] },
        because: {
          title: "Same bins, new word",
          explain: 'El-bin → "un." La-bin → "una." Same -o/-a cheat code.',
          key: '"Un" also means "one" — "un gato" = a cat OR one cat.',
          fun: "You now know FOUR words: el, la, un, una. Enough to label the world.",
          src: "Articles are the most common words in any language.",
        },
        practice: [
          { type: "pick", q: '"a cat"…', a: "un gato", w: ["una gato", "el gato", "una gata"], h: "gato → -o → un" },
          { type: "match", q: "Match them", pairs: [["a boy", "un niño"], ["a girl", "una niña"], ["a cat", "un gato"], ["a table", "una mesa"]] },
        ],
      },
      {
        id: "i_you",
        title: "I / you / he / she",
        emoji: "👤",
        en: ["I", "you", "he", "she"],
        es: "yo / tú / él / ella",
        pron: "yoh / too / ehl / EH-yah",
        note: "The core cast of any conversation.",
        clusters: [
          { e: "I", s: "yo" },
          { e: "you (casual)", s: "tú" },
          { e: "he", s: "él" },
          { e: "she", s: "ella" },
        ],
        because: {
          title: "Here's the twist",
          explain: 'In Spanish the verb ending tells you who — so they often skip the pronoun. "Como" already means "I eat."',
          key: 'They only say "yo" for emphasis — like "*I* did it."',
          fun: '"Yo quiero Taco Bell" — that yo is extra emphasis.',
          src: "Called a pro-drop language. Verbs carry so much info pronouns are optional.",
        },
        practice: [
          { type: "pick", q: '"I" in Spanish…', a: "yo", w: ["tú", "él", "ella"], h: "First person" },
          { type: "match", q: "Match pronouns", pairs: [["I", "yo"], ["you", "tú"], ["he", "él"], ["she", "ella"]] },
        ],
      },
      {
        id: "my_your",
        title: "my / your",
        emoji: "🏷️",
        en: ["my", "your"],
        es: "mi / tu",
        pron: "mee / too",
        note: "Claim your stuff.",
        clusters: [
          { e: "my house", s: "mi casa" },
          { e: "your name", s: "tu nombre" },
          { e: "my dog", s: "mi perro" },
          { e: "your mom", s: "tu mamá" },
        ],
        placement: { en: ["my", "house"], es: ["mi", "casa"] },
        because: {
          title: "Watch the accent",
          explain: '"Tú" (accent) = you. "Tu" (no accent) = your.',
          key: '"Mi" = my. "Tu" = your. No gender changes. Easy win!',
          fun: '"Mi casa es tu casa" — now you understand every word!',
          src: "With mi/tu + any noun you can talk about your world.",
        },
        practice: [
          { type: "pick", q: '"my house"…', a: "mi casa", w: ["tu casa", "mi nombre", "tu mamá"], h: "my = mi" },
          { type: "match", q: "Match", pairs: [["my house", "mi casa"], ["your name", "tu nombre"], ["my dog", "mi perro"], ["your mom", "tu mamá"]] },
        ],
      },
      {
        id: "this_that",
        title: "this / that",
        emoji: "👆",
        en: ["this", "that"],
        es: "este / ese",
        pron: "EHS-teh / EH-seh",
        note: "Point at things near and far.",
        clusters: [
          { e: "this book", s: "este libro", g: "m" },
          { e: "this house", s: "esta casa", g: "f" },
          { e: "that dog", s: "ese perro", g: "m" },
          { e: "that girl", s: "esa niña", g: "f" },
        ],
        because: {
          title: "Near vs. far + bins",
          explain: "Close = este/esta. Far = ese/esa. Same bin system.",
          key: "Close + el-bin = este. Close + la-bin = esta. Far + el-bin = ese. Far + la-bin = esa.",
          fun: "Spanish has THREE distances: este, ese, aquel (way over there)!",
          src: "This + that + right bin = point at anything.",
        },
        practice: [
          { type: "pick", q: '"this book" (libro = el-bin)…', a: "este libro", w: ["esta libro", "ese libro", "esa libro"], h: "Close + el-bin = este" },
          { type: "match", q: "Match", pairs: [["this book", "este libro"], ["this house", "esta casa"], ["that dog", "ese perro"], ["that girl", "esa niña"]] },
        ],
      },
    ],
  },
  {
    id: "connectors",
    title: "Connectors",
    sub: "Glue words together",
    emoji: "🔗",
    color: "#c4b5fd",
    lessons: [
      {
        id: "and_or",
        title: "and / or / but",
        emoji: "➕",
        en: ["and", "or", "but"],
        es: "y / o / pero",
        pron: "ee / oh / PEH-roh",
        note: "Three tiny words that unlock real thoughts.",
        clusters: [
          { e: "coffee and tea", s: "café y té" },
          { e: "yes or no", s: "sí o no" },
          { e: "small but strong", s: "pequeño pero fuerte" },
        ],
        placement: { en: ["coffee", "and", "tea"], es: ["café", "y", "té"] },
        because: {
          title: "Almost 1-to-1",
          explain: "No tricks. Plug them in same as English.",
          key: "Y = and. O = or. Pero = but.",
          fun: "Spanish hates repeated sounds — y becomes e before i-sounds, o becomes u before o-sounds!",
          src: "Universal logic. Combine any two ideas.",
        },
        practice: [
          { type: "pick", q: '"coffee AND tea" — which connector?', a: "y", w: ["o", "pero", "con"], h: "y = and" },
          { type: "match", q: "Match connectors", pairs: [["and", "y"], ["or", "o"], ["but", "pero"]] },
        ],
      },
      {
        id: "in_with",
        title: "in / on / with",
        emoji: "📍",
        en: ["in", "on", "with"],
        es: "en / con",
        pron: "ehn / kohn",
        note: "Where things are and who they're with.",
        clusters: [
          { e: "in the house", s: "en la casa" },
          { e: "on the table", s: "en la mesa" },
          { e: "with my friend", s: "con mi amigo" },
          { e: "coffee with milk", s: "café con leche" },
        ],
        placement: { en: ["coffee", "with", "milk"], es: ["café", "con", "leche"] },
        because: {
          title: "Two English words → one",
          explain: 'Both "in" and "on" = "en" in Spanish.',
          key: '"En" = in AND on. "Con" = with.',
          fun: "This is why Spanish speakers mix up in/on in English!",
          src: "Prepositions diverge the most between languages.",
        },
        practice: [
          { type: "pick", q: '"in the house" → "___ la casa"', a: "en", w: ["con", "el", "y"], h: "en = in" },
          { type: "match", q: "Match", pairs: [["in the house", "en la casa"], ["on the table", "en la mesa"], ["with my friend", "con mi amigo"], ["coffee with milk", "café con leche"]] },
        ],
      },
    ],
  },
  {
    id: "actions",
    title: "First Actions",
    sub: "Now you can DO things",
    emoji: "⚡",
    color: "#fbbf24",
    lessons: [
      {
        id: "is_are",
        title: "is / are",
        emoji: "🪞",
        en: ["is", "are"],
        es: "es / está",
        pron: "ehs / ehs-TAH",
        note: 'Two ways to say "is."',
        clusters: [
          { e: "She is tall.", s: "Ella es alta.", t: "always" },
          { e: "She is tired.", s: "Ella está cansada.", t: "now" },
          { e: "He is a doctor.", s: "Él es doctor.", t: "always" },
          { e: "He is sick.", s: "Él está enfermo.", t: "now" },
        ],
        placement: { en: ["She", "is", "tall"], es: ["Ella", "es", "alta"] },
        formula: {
          type: "decision",
          title: 'The "is" decision tree',
          question: "Always true — or just right now?",
          paths: [
            { label: "Always true (identity)", result: "ES", color: "#60a5fa", examples: ["She is tall → es alta", "He is a doctor → es doctor"] },
            { label: "Right now (state, mood)", result: "ESTÁ", color: "#fbbf24", examples: ["She is tired → está cansada", "He is sick → está enfermo"] },
          ],
        },
        because: {
          title: "The biggest mind-shift",
          explain: '"Es" = always true. "Está" = right now.',
          key: "Is this who they ARE, or how they HAPPEN TO BE? Always = es. Now = está.",
          fun: '"He is dead" uses ESTÁ — death is something that happened!',
          src: 'Latin "esse" (to exist) vs "stare" (to stand).',
        },
        practice: [
          { type: "pick", q: '"She is tall" (always) →', a: "es", w: ["está", "son", "están"], h: "Always = es" },
          { type: "pick", q: '"He is sick" (right now) →', a: "está", w: ["es", "son", "están"], h: "Temporary = está" },
          { type: "match", q: "Sort: ES vs ESTÁ", pairs: [["She is tall", "es (always)"], ["She is tired", "está (now)"], ["He is a doctor", "es (always)"], ["He is sick", "está (now)"]] },
        ],
      },
      {
        id: "want_need",
        title: "want / need",
        emoji: "🎯",
        en: ["want", "need"],
        es: "quiero / necesito",
        pron: "kee-EH-roh / neh-seh-SEE-toh",
        note: "Ask for things. Game-changer.",
        clusters: [
          { e: "I want water.", s: "Quiero agua." },
          { e: "I need help.", s: "Necesito ayuda." },
          { e: "I want to eat.", s: "Quiero comer." },
          { e: "I need to go.", s: "Necesito ir." },
        ],
        placement: { en: ["I", "want", "water"], es: ["Quiero", "agua"] },
        because: {
          title: "Survival verbs",
          explain: 'Straight like English: I want [thing]. Drop "yo" — the -o ending means "I."',
          key: '"Quiero" = I want. "Necesito" = I need. Stack verbs: "Quiero comer."',
          fun: '"Querer" also means to love — "Te quiero" = I love you.',
          src: "Nail these and you survive in any Spanish-speaking country.",
        },
        practice: [
          { type: "pick", q: '"I want water" — verb?', a: "Quiero", w: ["Necesito", "Tengo", "Estoy"], h: "want = quiero" },
          { type: "match", q: "Match", pairs: [["I want water", "Quiero agua"], ["I need help", "Necesito ayuda"], ["I want to eat", "Quiero comer"], ["I need to go", "Necesito ir"]] },
        ],
      },
      {
        id: "gustar",
        title: "like / enjoy",
        emoji: "☕",
        en: ["like", "enjoy"],
        es: "gustar",
        pron: "goos-TAHR",
        note: "This one works BACKWARDS.",
        clusters: [
          { e: "I like coffee.", s: "Me gusta el café." },
          { e: "You like music.", s: "Te gusta la música." },
          { e: "She likes dancing.", s: "A ella le gusta bailar." },
        ],
        placement: { en: ["I", "like", "coffee"], es: ["Me", "gusta", "el café"] },
        formula: {
          type: "flip",
          title: "The Flip Formula",
          enF: {
            label: "English: DOER → ACTION → THING",
            pieces: [
              { t: "I", r: "doer", c: "#60a5fa" },
              { t: "like", r: "action", c: "#c4b5fd" },
              { t: "coffee", r: "thing", c: "#fbbf24" },
            ],
          },
          esF: {
            label: "Spanish: RECEIVER → ACTION → DOER",
            pieces: [
              { t: "Me", r: "receiver", c: "#f472b6" },
              { t: "gusta", r: "action", c: "#c4b5fd" },
              { t: "el café", r: "doer!", c: "#fbbf24" },
            ],
          },
          rules: [
            "English: DOER → ACTION → THING",
            "Spanish: RECEIVER → ACTION → DOER",
            "Coffee does the action TO you",
            "You just receive it",
            "Verb matches the THING: gusta (1) / gustan (many)",
          ],
          examples: [
            { e: "I like dogs", s: "Me gustan los perros", n: "plural → gustan" },
            { e: "You like music", s: "Te gusta la música", n: "te = you receiving" },
            { e: "She likes dancing", s: "Le gusta bailar", n: "le = she receiving" },
          ],
        },
        because: {
          title: "The famous flip",
          explain: '"Me gusta el café" = Coffee does it for me. It gives you good vibes — you just receive it.',
          key: "Me (receiver) + gusta (does it for) + el café (the thing doing it).",
          fun: 'This is why Spanish speakers say "me like coffee" in English — receiver first!',
          src: 'From Latin "gustare" = to taste.',
        },
        becauseFlip: {
          title: "The English un-flip",
          explain: 'English "like" is direct — I do the liking. That\'s why you say "Me like" — now say "I like" every time.',
          key: "English: I (doer) + like (action) + coffee (thing). YOU are in charge.",
        },
        practice: [
          { type: "pick", q: "Who does the action in Spanish?", a: "Coffee (does it for me)", w: ["I (I do the liking)", "Nobody", "The barista"], h: "The THING does the action" },
          { type: "pick", q: '"I like coffee" →', a: "Me gusta el café", w: ["Yo gusto el café", "Yo gusta café", "Mi gusta café"], h: "me + gusta + el café" },
          { type: "match", q: "Match", pairs: [["I like coffee", "Me gusta el café"], ["You like music", "Te gusta la música"], ["She likes dancing", "Le gusta bailar"]] },
        ],
      },
      {
        id: "tener",
        title: "have / carry",
        emoji: "✊",
        en: ["have", "carry"],
        es: "tener",
        pron: "teh-NEHR",
        note: "You don't BE hungry — you CARRY it.",
        clusters: [
          { e: "I have a dog.", s: "Tengo un perro." },
          { e: "I'm hungry.", s: "Tengo hambre." },
          { e: "I'm 20 years old.", s: "Tengo 20 años." },
          { e: "I have to go.", s: "Tengo que ir." },
        ],
        placement: { en: ["I", "am", "hungry"], es: ["Tengo", "hambre"] },
        formula: {
          type: "flip",
          title: "The Carry Formula",
          enF: {
            label: "English: I + AM + adjective",
            pieces: [
              { t: "I", r: "doer", c: "#60a5fa" },
              { t: "am", r: "being", c: "#c4b5fd" },
              { t: "hungry", r: "adjective", c: "#fbbf24" },
            ],
          },
          esF: {
            label: "Spanish: I CARRY + noun",
            pieces: [
              { t: "Tengo", r: "I carry", c: "#60a5fa" },
              { t: "hambre", r: "hunger", c: "#fbbf24" },
            ],
          },
          rules: [
            "English: I + AM + [description]",
            "Spanish: I CARRY + [object]",
            "Hungry = an OBJECT you hold",
            "Same for: thirsty, afraid, cold, hot",
            "Age too: Tengo 20 años = carry 20 years",
          ],
          examples: [
            { e: "I'm thirsty", s: "Tengo sed", n: "carry thirst" },
            { e: "She's 25", s: "Tiene 25 años", n: "carries 25 years" },
            { e: "We have to leave", s: "Tenemos que ir", n: "carry obligation" },
          ],
        },
        because: {
          title: "You carry things",
          explain: "English: you ARE hungry. Spanish: you CARRY hunger — like holding it.",
          key: '"Tengo hambre" = carrying hunger. "Tengo 20 años" = carrying 20 years.',
          fun: 'This is why Spanish speakers say "I have hunger" in English!',
          src: 'Latin "tenēre" = to grip. Root of "tenant" and "tenacious."',
        },
        practice: [
          { type: "pick", q: '"I\'m hungry" uses…', a: "Tengo (carry)", w: ["Estoy (am)", "Soy (am)", "Quiero (want)"], h: "CARRY hunger" },
          { type: "match", q: "Match", pairs: [["I have a dog", "Tengo un perro"], ["I'm hungry", "Tengo hambre"], ["I'm 20", "Tengo 20 años"], ["I have to go", "Tengo que ir"]] },
        ],
      },
    ],
  },
];
